name: business_transactions
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^2.6.1

  riverpod_annotation: ^2.6.1

  freezed_annotation: ^2.4.4

  # manage svgs
  flutter_svg: ^2.1.0

  # DataBase
  hive_ce: ^2.0.0
  hive_ce_flutter: ^2.0.0

  # Generate RFC4122
  uuid: ^4.5.1

  # Provides internationalization and localization capabilities.
  intl: ^0.20.2

  lottie: ^3.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_ce_generator: ^1.9.2
  build_runner: ^2.4.15
  riverpod_generator: ^2.6.3
  riverpod_lint: ^2.6.3
  freezed: ^2.5.7
  flutter_launcher_icons: ^0.14.4


flutter:
  uses-material-design: true
  assets:
    - assets/vectors/
    - assets/lottie/

  fonts:
      - family: ProximaNova
        fonts:
          - asset: assets/fonts/proxima-nova.otf
            style: normal
            weight: 400
          - asset: assets/fonts/proxima-nova-medium-pu.otf
            weight: 500
          - asset: assets/fonts/proxima-nova-bold.otf
            weight: 700

dependency_overrides:
  analyzer_plugin: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#1e6a4f"
  adaptive_icon_foregorund: "assets/icon/app_icon_foreground.png"